### ISSUE TITLE
Error: Cannot find module './settings.json'] code: 'MODULE_NOT_FOUND'

### ISSUE THREAD

**Issue by DeltaNu1142** [chrisns/docker-node-sonos-http-api#109]
I'm attempting to get my newly-created settings.json file recognized on startup, to no avail. I have a directory on my main Synology volume mapped, with the settings.json file located in it... Folder is /docker/sonos/settings, and Mount Path is /app/settings. Type is rw. Presets, clips, and cache folders are also mapped. I've tested the container and it works great. Specifically, I've added a VoiceRSS API key to the settings.json folder and I'm trying to get the SAY command working. Instead, I'm getting the missing_api_key.mp3 each time.

Any help would be appreciated.

**Comment by chrisns** [comment]
hard to guess at what the synology config is, could you try providing some screenshots maybe?

**Comment by DeltaNu1142** [comment]
Yes, definitely... here you go:

Docker:
![Docker1](https://user-images.githubusercontent.com/77296070/142205579-06e37702-fbb4-4839-b7cc-6912ed5a6e4c.png)

Folders:
![Synology](https://user-images.githubusercontent.com/77296070/142205600-b7dd9398-e09a-431f-9ff9-8dd5ed1969b4.png)

Log (screen shot seems about as useful as a CSV):
![Log](https://user-images.githubusercontent.com/77296070/142206123-9b89535d-1fb8-4a27-b546-524335bded0d.png)

I have the bare `settings.json` file in the settings folder:

`{
  "voicerss": "myapikeyxxxxxxx"
}
`

Thanks for having a look.

**Comment by mhoogenbosch** [comment]
You made the same mistake as I did. You mounted /settings as a complete folder, you need to mount the settings.json file.

**Comment by DeltaNu1142** [comment]
> You made the same mistake as I did. You mounted /settings as a complete folder, you need to mount the settings.json file.

I see, thanks! I did mount those folders, as folders, individually... so what is the mount path for the settings.json file, and does it matter where the file resides?

**Comment by mhoogenbosch** [comment]
> > You made the same mistake as I did. You mounted /settings as a complete folder, you need to mount the settings.json file.
> 
> I see, thanks! I did mount those folders, as folders, individually... so what is the mount path for the settings.json file, and does it matter where the file resides?
> 
> EDIT: as I recall, I attempted to mount the file... but during startup, the log still shows, `Error: Cannot find module './settings.json'`.
> 
> I've just tried it again with this mounting scheme and encountered the same error: ![Error](https://user-images.githubusercontent.com/77296070/142222295-0b7d5dfb-b0d8-4b93-b476-63517a598a55.png)

honestly i don't know how synology works. I always created my dockers when running on syno trough cli. Nowdays i'm using docker-compose on a pi4? Within the container it is /app/settings.json , so not /app/settings/settings.json.. so maybe you just need to get rit of the additional settings folder.

**Comment by DeltaNu1142** [comment]
I believe I tried that when setting up, but just for kicks I just moved the
settings file to my "root" (sonos) folder and mounted it as
app/settings.json. No dice, unfortunately.

**Comment by mhoogenbosch** [comment]
Can you post another screenshot?

**Comment by DeltaNu1142** [comment]
> Can you post another screenshot?

Certainly! Thanks for having a look:
![Settings](https://user-images.githubusercontent.com/77296070/142232679-7fe4417a-4cd0-4f91-80b2-562928017caa.png)

**Comment by mhoogenbosch** [comment]
Seems rich but where did the probeert folders go?

**Comment by DeltaNu1142** [comment]
> Seems right but where did the probeert folders go?

Oh, I deleted them because I thought they might be redundant. I've just added them back and... same result. Can't find `settings.json` module.

Screen shot:
![Settings](https://user-images.githubusercontent.com/77296070/142233877-9550efe7-371b-4c89-ae0b-134c55ee4b86.png)

**Comment by mhoogenbosch** [comment]
It is /app/settings.json on the right part

**Comment by DeltaNu1142** [comment]
> It is /app/settings.json on the right part

Ah, thanks. Still not finding it during startup, though:
![Settings](https://user-images.githubusercontent.com/77296070/142236037-372267eb-ea96-4395-8318-c51aae80ec18.png)

**Comment by mhoogenbosch** [comment]
Mmmm only thing different is the settings folder, you don’t need that. But can’t imagine that’s responsible for this. But you could try that

**Comment by chrisns** [comment]
can you try ssh'ing in and start with the commandline?
i'm wondering how the synology gui is mapping volumes with its normal annotation of `/volumeN/share`

**Comment by DeltaNu1142** [comment]
I'm pretty terrible at Linux, but this is what I'm seeing:
![SSH](https://user-images.githubusercontent.com/77296070/142240810-1eedbffd-6d81-41d3-a5e9-6d4c2e755017.png)

**Comment by chrisns** [comment]
```
docker pull chrisns/docker-node-sonos-http-api
docker run \
  --net=host \
  --name sonos \
  --restart=always \
  -d \
  -v /volume1/docker/sonos/settings.json:/app/settings.json \
  -v /volume1/docker/sonos/clips:/app/static/clips \
  -v /volume1/docker/sonos/cache:/app/cache \
  -v /volume1/docker/sonos/presets:/app/presets \
  chrisns/docker-node-sonos-http-api
```

**Comment by DeltaNu1142** [comment]
On the very first command, I got:
`Using default tag: latest
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=chrisns%2Fdocker-node-sonos-http-api&tag=latest": dial unix /var/run/docker.sock: connect: permission denied`

**Comment by chrisns** [comment]
prefix the docker commands with `sudo`
so
```bash
sudo docker pull chrisns/docker-node-sonos-http-api
sudo docker run \
  --net=host \
  --name sonos \
  --restart=always \
  -d \
  -v /volume1/docker/sonos/settings.json:/app/settings.json \
  -v /volume1/docker/sonos/clips:/app/static/clips \
  -v /volume1/docker/sonos/cache:/app/cache \
  -v /volume1/docker/sonos/presets:/app/presets \
  chrisns/docker-node-sonos-http-api
```

**Comment by DeltaNu1142** [comment]
Thanks! That worked. I was concerned because the network tab doesn't have IP addresses discretely defined as before, but I've done a SAY test, and it's working well. Looks like the UI does something wonky with mapping... I appreciate your help with this.
