### ISSUE TITLE
docker run command wrong?

### ISSUE THREAD

**Issue by WhileDekker** [chrisns/docker-node-sonos-http-api#135]
Hi

really great work!

I just found one small thing in the documentation, which might be wrong:

On https://hub.docker.com/r/chrisns/docker-node-sonos-http-api

you specified one of the volumes like
  -v `pwd`/settings:/app/settings \

I guess it should be
  -v `pwd`/settings.json:/app/settings.json \

in your compose example its fine. Just sth with confused me ;-)

**Comment by chrisns** [comment]
depends, the instructions are based on creating a directory
closing the issue since as you say it works, please reopen if you disagree
thanks!

**Comment by WhileDekker** [comment]
In your code you create a settings folder and the settings.json outside the container.

inside the container you map settings => /app/settings which means the settings.json is in /app/settings/settings.json inside the container. 

when you start the container the sonos api will look for a file called /app/settings.json and it will fail. the api will work as it is also workign without that file, but any settings you maed in the settings.json is useless.

you specified it correctly on github but its wrong on hub.docker.com

**Comment by chrisns** [comment]
ah, understood!
thanks, great catch.
This must have broken when I stopped auto building from dockerhub and it fetched the readme automatically.
I'll manually copy paste now
thanks
