### ISSUE TITLE
Automated builds broken?

### ISSUE THREAD

**Issue by mjbnz** [chrisns/docker-node-sonos-http-api#139]
Heya, would be great if a refreshed docker image was built, but it looks like it's failed to build since you migrated to using your `repo-config` repository?

**Comment by chrisns** [comment]
Thanks for the prod about this! You're quite right I did break it and haven't fixed it yet. Will get on it ASAP

**Comment by chrisns** [comment]
@mjbnz sorry been super slow, have fixed/reverted
