### ISSUE TITLE
Say command no more working since new site voicerss 

### ISSUE THREAD

**Issue by Titof44** [chrisns/docker-node-sonos-http-api#14]
For aproximatly 3 weeks, command Say is no more working. I use voicerss. I think, since i had to 
 create again my account on voicerss (as a lot of people), the command is no more working. What i have notice is the voicexxxx. mp3 is created on docker and sent to sonos but on sonos i see error not well encoded.
If i copy the files on a windows folder, i can run it on VLC and sound is ok !!!
If i copy the file on library sonos it does not work but if i change the extension mp3 to wav, it is working on sonos !!!

Can you help me, perhaps 22khz_16bit_mono for mp3 is no more suported by Sonos but i can't change encoded term and extension of the file on voicerss.js.
Can we have it on settings.json like language or API Key ?

Thanks for helping me.

**Comment by chrisns** [comment]
Hey,
not sure, make sure you're using the latest image?
see https://github.com/jishi/node-sonos-http-api/pull/687/commits/7fc74e8f46c341f2458626b3ab392ea671255db8
and https://github.com/jishi/node-sonos-http-api/issues/682
it's not specifically an issue with the docker image though
