### ISSUE TITLE
arm64/arm images

### ISSUE THREAD

**Issue by vchrisb** [chrisns/docker-node-sonos-http-api#19]
It would be great if images on docker hub would also be available for arm64/arm.
The Dockerfile works without any modification to build for arm64.

I use for this on Mac:
```
export IMAGE="node-sonos-http-api"
export VERSION="snapshot"
docker buildx create --name mybuilder
docker buildx use mybuilder
docker buildx inspect --bootstrap
docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 . -t vchrisb/${IMAGE}:${VERSION} --push
```

**Comment by chrisns** [comment]
Sure. It’s been on my todo for a while. buildx makes it way easier. Will sort it out

**Comment by chrisns** [comment]
should all work now, give it a whirl!

**Comment by vchrisb** [comment]
awesome! Thx! 🥇
