### ISSUE TITLE
More instructions?

### ISSUE THREAD

**Issue by NathanMaton** [chrisns/docker-node-sonos-http-api#2]
The readme here wasn't very helpful for someone new to Docker. Any chance you could add some more info for those of us who aren't Docker experts? Thanks!

**Comment by chrisns** [comment]
Hey, sorry for not seeing this, did you manage to stand it up, did you get issues with the usage description, if not could you describe what your setup is and I'll try to improve the docs accordingly.
Thanks
Chris
