### ISSUE TITLE
Unable to play 'google-60bc2345a7878b38383deoeowo3-Joanna.mp3' - the song is not encoded correctly.

### ISSUE THREAD

**Issue by nodecentral** [chrisns/docker-node-sonos-http-api#3]
Hi

I have the Docker up and running on my QNAP (in Bridge mode so it is given an IP) and I'm trying to use it with Polly Amazon TTS. I have the settings.json updated with my Amazon credentials..

I am sending a request through in the follow format

`192.168.1.173:5005/kitchen/say/This%20is%20a%20test%20of%20Polly,%20the%20Amazon%20speech%20engine./Joanna/60`

If I look at the Sonos app I can see it respond by moving off what is currently in the queue -  but it quickly  returns an error. An example of which is below/in the subject line.

Unable to play 'google-60bc2345a7878b38383deoeowo3-Joanna.mp3' - the song is not e coded correctly.

**Comment by nodecentral** [comment]
Self diagnosis- so far ..

The fact it shows Google (which is default TTS) suggests this settings.json was not being picked up, and as a side note, maybe the default Google service is it working too.

As settings.json needs to be in root, that perhaps not as easy as I thought to find when you are using a Docker/container

**Comment by chrisns** [comment]
Sorry, didn't see this The `settings.json` should bind in via a symlink if you start it according to the usage in the readme. did you find a fix for this in the end?

**Comment by nodecentral** [comment]
Hi, thanks for replying.

I am using a Docker, but couldn’t see where the setting.json symlink was pointing to so in the end I  renamed symlink and then uploaded my customised json and everything seems to be working fine -my Amazon Polly integrations is working well.

Have I now screwed something up by changing the symlink in that folder ?

**Comment by chrisns** [comment]
not entirely sure what you've done without seeing your code.
going to close the issue since it sounds like you got it going anyway but feel free to give me a bit more info and I'll try to help :)
