### ISSUE TITLE
Presets Volume Configuration

### ISSUE THREAD

**Issue by ucdscott** [chrisns/docker-node-sonos-http-api#347]
Thank you for maintaining this wonderful Docker image!

I'm attempting to map the presets folder to an external volume so that my preset json files persist but I'm doing something wrong.

I thought the presets folder inside of the container was:

/usr/local/lib/node_modules/node-sonos-http-api/presets

but when I map it using Synology Container Manager:

![image](https://github.com/chrisns/docker-node-sonos-http-api/assets/33180936/0f66dc73-f54a-4016-834f-576e4ecd54b7)

my preset (hubitatTTS) isn't found:

![image](https://github.com/chrisns/docker-node-sonos-http-api/assets/33180936/4125c9fd-4477-43e2-9bf3-d378686e7764)

What am I doing wrong?

**Comment by chrisns** [comment]
see the `readme.md` you're mapping the wrong directory container side, it should be `:/app/presets` not the `/usr/lib/....` no idea where you got that from?

**Comment by ucdscott** [comment]
That worked! Much appreciated.
