### ISSUE TITLE
Update existing installation ?

### ISSUE THREAD

**Issue by nodecentral** [chrisns/docker-node-sonos-http-api#4]
Hi

Thanks for maintaining this app within a Docker

 I’ve had this installed for a number of months now and was wondering how I could update it , without having to remove and reinstall and customise the settings.json again ?

**Comment by chrisns** [comment]
Hi,
Glad you're getting some use out of it.
If you've followed the guide on starting it with a volume mounted `settings.json` you should be able to simply `docker stop ...`, `docker pull ...`, `docker run...`.
Hope that helps
Thanks

**Comment by nodecentral** [comment]
Hi

Thanks for responding, I installed the Docker on my QNAPs NAS via their Container Station app. By any chance do you have an experience with that route ?

**Comment by chrisns** [comment]
Sorry, no.
No idea how it works, but if you can connect via ssh you may be able to use the commands I described in the readme
