### ISSUE TITLE
Docker Swarm

### ISSUE THREAD

**Issue by murmeltier08** [chrisns/docker-node-sonos-http-api#46]
Hello I can not mount the volumns:

version: "3"
services:
  sonos:
    image: chrisns/docker-node-sonos-http-api:latest
    volumns:
      - /my/path/settings:/app/settings
    networks:
      - outside
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=sonos.p.cns.me
        - com.df.servicePath=/
        - com.df.port=5005
networks:
  outside:
    external:
      name: "host"

I get the Error message in portainer:
![Bildschirmfoto 2020-12-22 um 15 38 11](https://user-images.githubusercontent.com/44034211/102900028-0a021f00-446c-11eb-827a-aaad40d49995.png)

Did someone have a Idea?

**Comment by chrisns** [comment]
Typo. 'volumes' not 'volumns'

**Comment by murmeltier08** [comment]
Thank you! I did not see it...
