### ISSUE TITLE
docker build step in readme

### ISSUE THREAD

**Issue by rr-kalbeck** [chrisns/docker-node-sonos-http-api#5]
i'm new to docker and was a bit confused by the readme. doesn't it need a step for building the docker image?

eg-
build image. run the following from directory with Dockerfile
```
$ docker build -t <your username>/docker-node-sonos-http-api .
```

**Comment by chrisns** [comment]
Hi
Only if you want to build it, if you just do a docker run it will put it from the docker hub repository.

**Comment by rr-kalbeck** [comment]
ah ok, thanks
