### ISSUE TITLE
port forwarding

### ISSUE THREAD

**Issue by rr-kalbeck** [chrisns/docker-node-sonos-http-api#6]
i'm using docker for mac and trying to enable port forwarding by adding the -p 8080:5005
it doesn't  work :(

```
docker run \
  --net=host \
  --name sonos \
  --restart=always \
  -d \
  -p 8080:5005 \
  -v `pwd`/settings:/app/settings \
  -v `pwd`/clips:/app/static/clips \
  -v `pwd`/cache:/app/cache \
  -v `pwd`/presets:/app/presets \
  chrisns/docker-node-sonos-http-api 
```

am i doing something wrong?

![image](https://user-images.githubusercontent.com/32479606/33125617-7df3d0ce-cf81-11e7-8f5f-f588a34c4576.png)

**Comment by chrisns** [comment]
Hi.
You don't need to / won't be able to forward the port since you've specified the `--net=host` which it needs for discovery.

**Comment by chrisns** [comment]
it will be on the default port (5005) or another one if you specified different in a settings.json
