### ISSUE TITLE
Install in docker on QNAP NAS

### ISSUE THREAD

**Issue by davidkm123** [chrisns/docker-node-sonos-http-api#7]
Hello,
I would like to install your docker on my QNAP NAS. Container Station is available for creation, but I do not know how to set up this docker. Can you help me please?

Thanks

David

**Comment by chrisns** [comment]
Hi,
Sorry I'm not familiar with that, I imagine if you have ssh access to the NAS you may be able to run the commands in the readme and it should work, i'm not sure if you'll then be able to then manage it in the 'Container Station' interface though.
Thanks
