### ISSUE TITLE
Time zone in docker-node-sonos-http-api not correct

### ISSUE THREAD

**Issue by GerhardLang** [chrisns/docker-node-sonos-http-api#89]
Hi, synology and docker do have correct timezone.
In this container even an environment setting in portainer does not help as it did with other containers.

My compose file:

services:
  sonoshttp:
    image: chrisns/docker-node-sonos-http-api
    container_name: sonoshttp
    network_mode: host
    restart: always
    volumes:
      - /volume1/docker/sonoshttp/settings:/app/settings
      - /volume1/docker/sonoshttp/clips:/app/static/clips
      - /volume1/docker/sonoshttp/cache:/app/cache
      - /volume1/docker/sonoshttp/presets:/app/presets
    environment:
      - TZ=Europe/Amsterdam

Do you have any further idea?

thank you a lot.
Gerhard

**Comment by chrisns** [comment]
It's an alpine base image

You may be able to volume Mount in like

https://github.com/gliderlabs/docker-alpine/issues/136#issuecomment-821832825

If not I'll add the package to the image, let me know

**Comment by GerhardLang** [comment]
Hi, 
Unfortunately will volume mount of timezone or TZ not work:
We do have 9:48 and log shows still -2 hours:

2021-09-04T07:48:46.817Z INFO Could not find file /app/settings.json
2021-09-04T07:48:46.921Z INFO Presets loaded: {
  example: {
    players: [
      { roomName: 'Wohnung', volume: 10 },
      { roomName: 'Wintergarten', volume: 10 }
    ],
    playMode: { shuffle: true, repeat: 'all', crossfade: false },
    pauseOthers: false
  }
}

If you might add timezone support will be appreciated. 
Will this work with the original idea of setting environment variable TZ?
Thanks.
Gerhard

**Comment by GerhardLang** [comment]
Hi, as I read UTC seems to be a docker standard on synology.
So I have to live with it I think. Thanks for help.
