### ISSUE TITLE
Error - standard_init_linux.go:190: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by jayheavner** [chrisns/docker-node-sonos-http-api#9]
Hi, I'm trying to run your container on a raspberry pi and I'm getting the following error.

`standard_init_linux.go:190: exec user process caused "exec format error"`

Any ideas?

**Comment by chrisns** [comment]
Hi,
Yes, you're trying to run a docker image built for x64 processor on an arm32 processor.
I see @joshendriks forked this repo and the repo name suggests it may work on a pi, you could give a go https://github.com/joshendriks/docker-raspberry-node-sonos-http-api

**Comment by jayheavner** [comment]
Yeah, I figured it was an architecture issue. Thanks, I'll check the fork.
